# Modules build script.

from waflib import Errors
import os

def configure(cfg):
    pass

def build(bld):
    platforms = bld.env.PLATFORMS
    for platform in platforms:
        name = os.path.basename(platform)
        _env = bld.all_envs['platform-' + name].derive()
        if _env.BUILD_MODULES:
            bld.stlib(source = bld.path.ant_glob('*/src/**') + bld.path.ant_glob('*/targets/' + _env.TARGET + '/**'), target = 'modules-' + name, env = _env)
    bld.install_files('${PREFIX}/include/flipper/', bld.path.ant_glob('*/include/flipper/**'))
