[package]
name = "flipper"
version = "0.1.0"
authors = ["Nick Mosher <nicholastmosher@gmail.com>"]

[dependencies]
clap = "2"
rustyline = "1.0.0"
lazy_static = "0.2"
flipper-rust = { path = "../languages/rust" }

[[bin]]
name = "flipper"
path = "src/flipper.rs"
test = false
doc  = false
