[package]
name = "flipper-console"
version = "0.1.0"
authors = ["Nick Mosher <nicholastmosher@gmail.com>"]

[dependencies]
clap = { version = "2", features = ["yaml"] }
flipper-bindings = { path = "../languages/rust" }

[[bin]]
name = "flipper-console"
path = "src/bin/flipper.rs"
test = false
doc  = false
