# Libflipper build script.

from waflib import Errors
import platform
import os

def configure(cfg):
	pass

def build(bld):
	platforms = bld.env.PLATFORMS
	for plat in platforms:
		name = os.path.basename(plat)
		_env = bld.all_envs['platform-' + name].derive()
		# Even though none of the symbols are used, include them in the shared library.
		if (platform.system() == 'Darwin'):
			_env.append_value('LDFLAGS', '-Wl,-all_load')
		elif (platform.system() == 'Linux'):
			_env.STLIB_MARKER = '-Wl,--whole-archive'
			_env.SHLIB_MARKER = '-Wl,--no-whole-archive'
		if _env.BUILD_LIBFLIPPER:
			bld.stlib(source = bld.path.ant_glob('src/**'), target = 'flipper-' + name, env = _env)
