# Console build script.

def configure(cfg):
    pass

def build(bld):
    bld.program(source = bld.path.ant_glob('src/**'), target = 'flipper', name = 'console', use = 'flipper platform-fvm', env = bld.all_envs['platform-posix'])
