# Console build script.

def configure(cfg):
    # Load the appropriate C compiler.
    cfg.load('compiler_c')

def build(bld):
    bld.program(source = bld.path.ant_glob('src/**'), target = 'flipper', name = 'console', use = 'libflipper platform-fvm', env = bld.all_envs['platform-posix'])
